version: "3.9"

networks:
  os-net:
    name: os-net

services:
  opensearch:
    image: opensearchproject/opensearch:3
    container_name: os
    hostname: opensearch
    environment:
      - discovery.type=single-node
      # Segurança HABILITADA (padrão). Define a senha inicial do usuário 'admin'.
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Admin123!ChangeMe
      # Heap (ajuste se precisar)
      - OPENSEARCH_JAVA_OPTS=-Xms2g -Xmx2g
    ulimits:
      memlock: { soft: -1, hard: -1 }
    ports:
      - "9201:9200"   # HTTPS
      - "9600:9600"
    volumes:
      - osdata:/usr/share/opensearch/data
    networks: [os-net]
    healthcheck:
      # -k para ignorar certificado autoassinado (LAB)
      test: ["CMD-SHELL", "curl -kfsS https://localhost:9200/_cluster/health | grep -E '\"status\":\"(yellow|green)\"'"]
      interval: 10s
      timeout: 5s
      retries: 30

  dashboards:
    image: opensearchproject/opensearch-dashboards:3
    container_name: os-dashboards
    environment:
      # Aponta para o serviço "opensearch" via HTTPS
      - OPENSEARCH_HOSTS=["https://opensearch:9200"]
      # Credenciais padrão do plugin Security (usuário admin)
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=Admin123!ChangeMe
      # Ignora verificação do certificado (autoassinado no LAB)
      - OPENSEARCH_SSL_VERIFICATIONMODE=none
      # (Opcional) para acessar de outra máquina
      - SERVER_HOST=0.0.0.0
    ports:
      - "5602:5601"
    depends_on:
      opensearch:
        condition: service_healthy
    networks: [os-net]

volumes:
  osdata: {}
